### ISSUE TITLE
Hierarchical Access Management

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#315]
**Description**: There is a requirement to provide hierarchical access control to Namespaces.

A `dataset` is owned by an Org and Org Unit.

One or more `products` can be associated with a `dataset`.

New requirements:
* A `product environment` can not be enabled (on the directory) until the Namespace has been assigned to an Org and Org Unit and the Dataset that is associated with that `product environment` matches this Org/Org Unit.
* An un-enabled `product environment` can be previewed on the API Directory by users with access to the related `namespace` (the "draft" should have an indicator on the API Directory describing this)
* A User with a Data Custodian role can be associated with an Org or Org Unit
* The "Data Custodian" role  has the permission to assign Namespaces to the Org or Org Unit
* The "Data Custodian" role has the permission to grant others to the Data Custodian role for that particular Org and Org Unit
* The "Data Custodian" role has the permission to grant Namespace permissions to other users
* The "Data Custodian" role is inherited by Group hierarchy based on Org and Org Unit

**Tasks:**
* [x] Design spike for backend
* [x] UX updates
* [x] Implement business rules for active environment
* [x] Unit tests
* [ ] Implement UX updates

**Comment by ikethecoder** [comment]
Draft UI change for Namespace Access - pending UX design:

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/b43a3362-e75e-4651-89ee-0cf271529a34)

**Comment by ikethecoder** [comment]
Draft OpenApi: https://openapi.apps.gov.bc.ca/?url=https://api-services-portal-feature-org-control.apps.silver.devops.gov.bc.ca/ds/api/openapi.yaml

**Comment by ikethecoder** [comment]
Feature branch testing: https://api-services-portal-feature-org-control.apps.silver.devops.gov.bc.ca/

**Comment by JohnathanBrammall** [comment]
Moving to Product Backlog for implementation prioritization for the UI. Work already completed for the API.
