### ISSUE TITLE
Release 1.1.1 regression testing issues Iter 3

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#370]
**Tasks:**

- [x] Masking of log data
- [x] If a user has `GroupAccess.Manage` at the top node and leaf node, they should be able to call `/organizations/{org}/roles` at a mid-node
- [x] When updating org access, getting error for data:

```
{
  "name": "ministry-of-citizens-services",
  "parent": "/ca.bc.gov",
  "members": [
  ]
}
-- organization mismatch error
```

- [x] For namespace deletion, include the removal of Service/Routes by calling the gwa-api
- [x] Update the gwa-api to provide the "default" permissions for namespaces
- [x] Consumer scopes not being found properly (RESOLVED - Scope entered with a SPACE in the Authorization Profile)

```
info: [whitelist] HIT : [78b1987847e9566263124c3b003f06bd] "\n  mutation ToggleConsumerScopes(\n    $prodEnvId: ID!\n    $consumerUsername: String!\n    $scopeName: String!\n    $grant: Boolean!\n  ) {\n    updateConsumerScopeAssignment(\n      prodEnvId: $prodEnvId\n      consumerUsername: $consumerUsername\n      scopeName: $scopeName\n      grant: $grant\n    )\n  }\n"
debug: [authz] *** ACCESS *** (updateConsumerScopeAssignment):(undefined) L=undefined F=undefined [, undefined] undefined by acope@idir
debug: [authz] --> FILTER {"product":{"namespace":"sp42-test"}}
debug: [keystone.prod-env] [lookupEnvironmentAndIssuerUsingWhereClause] WHERE {"AND":[{"id":"213"},{"product":{"namespace":"sp42-test"}}]}
debug: [keystone.prod-env] [lookupEnvironmentAndIssuerUsingWhereClause] result {"data":{"allEnvironments":[{"id":"213","name":"dev","approval":false,"legal":null,"credentialIssuer":{"name":"SP42 IdP Integration","flow":"client-credentials","mode":"auto","availableScopes":"[\"read\",\" write\"]","clientRoles":"[]","resourceType":"","resourceAccessScope":"","environmentDetails":"[{\"environment\":\"dev\",\"issuerUrl\":\"https://dev.oidc.gov.bc.ca/auth/realms/xtmke7ky\",\"clientRegistration\":\"managed\",\"clientId\":\"aps-sp42-integration\",\"clientSecret\":\"****\"}]"}}]}}
debug: [kc.client] [listDefaultClientScopes]
debug: [kc.client] [listDefaultClientScopes] RESULT [{"id":"00925d55-5e33-4ae9-be16-426da1c22e42","name":"role_list"},{"id":"066b16d0-1480-4c7e-be76-66c4d3a92ff5","name":"profile"},{"id":"fcef9e09-8a96-4a8a-9c34-e7adbb5c81b5","name":"email"},{"id":"867d7e13-2c33-4fff-84d8-2c1b93dec325","name":"roles"},{"id":"eb6be080-754d-4cad-8123-71ae52f2d004","name":"web-origins"},{"id":"02707e72-04df-4133-8889-c4e0d1caf551","name":"System/MedicationRequest.*"},{"id":"4a395efa-b1cf-405d-a53c-84125dc1ae8c","name":"System/Patient.*"},{"id":"ccf9f12d-966f-4ae5-bab4-70697c56085e","name":"sp30-admin"},{"id":"4c346b12-fdcf-42e0-9da9-6cfd6590dcef","name":"write"},{"id":"f910dd2b-cfbc-4db8-8fe7-b0dd1ace72d9","name":"read"}]
error: [ext.ConsumerScopesRoles] [updateConsumerScopeAssignment] Failed to update AssertionError [ERR_ASSERTION]: Scope not found in IdP
{"level":50,"time":1649711159532,"pid":24,"hostname":"bcgov-aps-portal-generic-api-7cc8dbd797-nvj6k","name":"graphql","message":"Scope not found in IdP","locations":[{"line":8,"column":5}],"path":["updateConsumerScopeAssignment"],"uid":"cl1v7fhey00060o825jza8nuc","name":"GraphQLError","generatedMessage":false,"code":"ERR_ASSERTION","actual":0,"expected":1,"operator":"strictEqual","stack":"dist/lists/extensions/ConsumerScopesAndRoles.js:168:49\nGenerator.next (<anonymous>)\nfulfilled (dist/lists/extensions/ConsumerScopesAndRoles.js:5:58)\nrunMicrotasks (<anonymous>)\n"}
```

- [x] Getting activity when there are gateway configuration activity, it's giving an Internal Error
- [x] Once a namespace is deleted, do not allow it to be created again
