### ISSUE TITLE
Retest the defects fixed in PR # 716

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#729]
- [x] Fixes The credential issuer failing to create when owner email is provided #718
            Updated Existing automation scripts

- [x] Fixes Credential issuer failing to create when inheritFrom name is provided #719
            

- [x] Fixes Failing to generate credentials #720

- [x] Fixes ACL plugin with invalid allow group giving invalid string error #721

- [x] Fixes Plugin template missing aud for shared idp #722

**Comment by nirajCITZ** [comment]
Defect #720 is blocked due to defect #734
